services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: matcha-backend
        container_name: matcha-app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "8000:80"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: matcha_db
            DB_USERNAME: matcha_user
            DB_PASSWORD: matcha_password
        volumes:
            - ./:/var/www/html
        networks:
            - matcha-network

    db:
        container_name: matcha-mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: matcha_db
            MYSQL_USER: matcha_user
            MYSQL_PASSWORD: matcha_password
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - matcha-network

networks:
    matcha-network:
        driver: bridge

volumes:
    mysql_data:
